### ISSUE TITLE
IS and FID

### ISSUE THREAD

**Issue by ScottWong98** [wtliao/text2image#1]
Hello, could you share the code for calculating the IS and FID ? I want to use this metric to evaluate my method.

**Comment by wtliao** [comment]
Hi, I have updated the repo for evaluation.

**Comment by cookie-ke** [comment]
Could you please put the image data into a folder when I want to use FID, LPIPS, or IS? The train set and data set are split by ".pikle" files and I don't know how to the evaluation indicator.
