### ISSUE TITLE
inference.py file

### ISSUE THREAD

**Issue by Cm744** [wtliao/text2image#12]
Hi there,
 A brilliant work! Thanks.

I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.

**Comment by wtliao** [comment]
Hi, the inference function is also in main.py , the gen_sample() function. You can just change cfg.B_VALIDATION=True for generating images for all captions of a data set. Or you can manually set the captions in the gen_sample() function (line 176) to generate the specific images. You also can set to use fixed/different noise to generate images (line238-244).

**Comment by priyankaupadhyay090** [comment]
> Hi there, A brilliant work! Thanks.
> 
> I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.

hey, did you get any error while running main.py ? I am facing some problem

**Comment by Cm744** [comment]
> > Hi there, A brilliant work! Thanks.
> > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> 
> hey, did you get any error while running main.py ? I am facing some problem

I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.

**Comment by priyankaupadhyay090** [comment]
> > > Hi there, A brilliant work! Thanks.
> > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > 
> > 
> > hey, did you get any error while running main.py ? I am facing some problem
> 
> I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.

I am getting few errors while running the main.py
could you please help me to figure it out ? We can connect thorough email if you would like

**Comment by Cm744** [comment]
> > > > Hi there, A brilliant work! Thanks.
> > > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > > 
> > > 
> > > hey, did you get any error while running main.py ? I am facing some problem
> > 
> > 
> > I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.
> 
> I am getting few errors while running the main.py could you please help me to figure it out ? We can connect thorough email if you would like

Yes, but I just ran main.py for inference/predict, I didn't run it for training

**Comment by priyankaupadhyay090** [comment]
> > > > > Hi there, A brilliant work! Thanks.
> > > > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > > > 
> > > > 
> > > > hey, did you get any error while running main.py ? I am facing some problem
> > > 
> > > 
> > > I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.
> > 
> > 
> > I am getting few errors while running the main.py could you please help me to figure it out ? We can connect thorough email if you would like
> 
> Yes, but I just ran main.py for inference/predict, I didn't run it for training

okay, can you help me with the inference then :) how did you do it speifically ?

**Comment by wtliao** [comment]
> > > Hi there, A brilliant work! Thanks.
> > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > 
> > 
> > hey, did you get any error while running main.py ? I am facing some problem
> 
> I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.

Hi， thanks for playing around with my work. Could you let me know what captions have you input for the bad results? Notes that, if the input caption refers to multiple objects, such as in the coco dataset, the output would not be good, which is an open challenge in this fied.

**Comment by Cm744** [comment]
> 

I input "a woman is using a laptop", "a car and a dog in the snow field ",etc

**Comment by Cm744** [comment]
> > > > Hi there, A brilliant work! Thanks.
> > > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > > 
> > > 
> > > hey, did you get any error while running main.py ? I am facing some problem
> > 
> > 
> > I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.
> 
> Hi， thanks for playing around with my work. Could you let me know what captions have you input for the bad results? Notes that, if the input caption refers to multiple objects, such as in the coco dataset, the output would not be good, which is an open challenge in this fied.

I input "a woman is using a laptop", "a car and a dog in the snow field ",etc

**Comment by Cm744** [comment]
> > > > > > Hi there, A brilliant work! Thanks.
> > > > > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > > > > 
> > > > > 
> > > > > hey, did you get any error while running main.py ? I am facing some problem
> > > > 
> > > > 
> > > > I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.
> > > 
> > > 
> > > I am getting few errors while running the main.py could you please help me to figure it out ? We can connect thorough email if you would like
> > 
> > 
> > Yes, but I just ran main.py for inference/predict, I didn't run it for training
> 
> okay, can you help me with the inference then :) how did you do it speifically ?

I have sent you an email, including detailed and specific guidance of doing inference. I will be more grateful if you can share the train/test split of Flickr8K data for S2IGAN repo. I am trying to run codes on Flickr8K dataset. If applicable, could you please share me the specific and detailed steps to generate train/test split of a custom dataset? The more specific the better, just like the inference steps I teach you.

Btw, have you run Speech-to-image S2IGAN on Flickr8K? Have you already had the trained model weights? If so, could you please share them with me ? So that I can do inference directly without training.

Thanks!

**Comment by wtliao** [comment]
> > > > > Hi there, A brilliant work! Thanks.
> > > > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > > > 
> > > > 
> > > > hey, did you get any error while running main.py ? I am facing some problem
> > > 
> > > 
> > > I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.
> > 
> > 
> > Hi， thanks for playing around with my work. Could you let me know what captions have you input for the bad results? Notes that, if the input caption refers to multiple objects, such as in the coco dataset, the output would not be good, which is an open challenge in this fied.
> 
> I input "a woman is using a laptop", "a car and a dog in the snow field ",etc

Yes, the existing methods are still suffering from synthesizing complex scenes which have multiple objects. In the paper, I have also discussed that. To my best knowledge, the existing methods have made great progress in synthesizing single objects. That is why the CUB dataset is so popular in this field.

**Comment by priyankaupadhyay090** [comment]
> > > > > > > Hi there, A brilliant work! Thanks.
> > > > > > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > > > > > 
> > > > > > 
> > > > > > hey, did you get any error while running main.py ? I am facing some problem
> > > > > 
> > > > > 
> > > > > I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.
> > > > 
> > > > 
> > > > I am getting few errors while running the main.py could you please help me to figure it out ? We can connect thorough email if you would like
> > > 
> > > 
> > > Yes, but I just ran main.py for inference/predict, I didn't run it for training
> > 
> > 
> > okay, can you help me with the inference then :) how did you do it speifically ?
> 
> I have sent you an email, including detailed and specific guidance of doing inference. I will be more grateful if you can share the train/test split of Flickr8K data for S2IGAN repo. I am trying to run codes on Flickr8K dataset. If applicable, could you please share me the specific and detailed steps to generate train/test split of a custom dataset? The more specific the better, just like the inference steps I teach you.
> 
> Btw, have you run Speech-to-image S2IGAN on Flickr8K? Have you already had the trained model weights? If so, could you please share them with me ? So that I can do inference directly without training.
> 
> Thanks!

I have shared you the very detailed code exlaining everyting to generate train/test split for a custom dataset and to generate pickle files for images and for class_info.

**Comment by freAK14** [comment]
> > > > > > > Hi there, A brilliant work! Thanks.
> > > > > > > I would be more grateful if you can provide the inference.py, sometimes also called predict.py, by which I can generate image of any input sentence.
> > > > > > 
> > > > > > 
> > > > > > hey, did you get any error while running main.py ? I am facing some problem
> > > > > 
> > > > > 
> > > > > I ran main.py as the inference, with any input text to generate images. There was no error but... the images were very bad....not as accurate as I expected.
> > > > 
> > > > 
> > > > I am getting few errors while running the main.py could you please help me to figure it out ? We can connect thorough email if you would like
> > > 
> > > 
> > > Yes, but I just ran main.py for inference/predict, I didn't run it for training
> > 
> > 
> > okay, can you help me with the inference then :) how did you do it speifically ?
> 
> I have sent you an email, including detailed and specific guidance of doing inference. I will be more grateful if you can share the train/test split of Flickr8K data for S2IGAN repo. I am trying to run codes on Flickr8K dataset. If applicable, could you please share me the specific and detailed steps to generate train/test split of a custom dataset? The more specific the better, just like the inference steps I teach you.
> 
> Btw, have you run Speech-to-image S2IGAN on Flickr8K? Have you already had the trained model weights? If so, could you please share them with me ? So that I can do inference directly without training.
> 
> Thanks!

Hey can you mail me the same thing at akashsocial14@gmail.com. I am learning this thing for my college project, facing issue in inference part.
