### ISSUE TITLE
Where is the global attention file?

### ISSUE THREAD

**Issue by cookie-ke** [wtliao/text2image#2]
![image](https://user-images.githubusercontent.com/56613566/121535437-c0ff5080-ca34-11eb-84b7-b252719f01b3.png)
![image](https://user-images.githubusercontent.com/56613566/121535457-c5c40480-ca34-11eb-8cad-9715ffd55ec9.png)

**Comment by wtliao** [comment]
@cookie-ke hi, sorry for my mistake. I have added the GlobalAttention.py file. Please let me know if you find more problems. Thanks!

**Comment by cookie-ke** [comment]
Thanks a lot!!!
