### ISSUE TITLE
The question of "main.py"

### ISSUE THREAD

**Issue by cookie-ke** [wtliao/text2image#3]
I am just a little confused about Why do you write like that. When I run the code if I don't change the 600 to 550, there may be occurred an error.
![image](https://user-images.githubusercontent.com/56613566/121792777-9b886780-cc2b-11eb-9672-97dbde3e5837.png)
![image](https://user-images.githubusercontent.com/56613566/121792810-f752f080-cc2b-11eb-8d6a-62ab14b90142.png)

**Comment by wtliao** [comment]
@cookie-ke 
sorry, I forget to modify it. I set it for debuging only. You can change it as you need.
