### ISSUE TITLE
missing 'opts.py' file

### ISSUE THREAD

**Issue by andyjung12** [wtliao/text2image#9]
I want to try training by using opts.py, which was mentioned on README.md. But it seems that the file is missing.

**Comment by wtliao** [comment]
Hi @andyjung12 , could you tell me where the opts.py file is required. I have modified locally but forget to update here. Please try to comment the "import opts" line.

**Comment by andyjung12** [comment]
![캡처](https://user-images.githubusercontent.com/85011867/135390539-db9a402a-4898-45d2-8e8d-c1401c2b1463.PNG)
As in the READ.ME, it says to see opts.py for the options for training. So, I tried to refer to that opts.py file, but it is not there.

**Comment by wtliao** [comment]
@andyjung12 sorry for forgetting to update that. Just ignore it. Directly refer main.py file for training and generating images using trained model.
